In [15]:
import numpy as np

In [16]:
cofficients = [1,-8/3,0]

<span style="background-color:green">X**2 - x*10/3 +0=0<span>
<br>
(x=0), (x=10/3)

In [31]:
from sympy import symbols, Eq, solve, Matrix, re, simplify

def get_Eigens(matrix):

    def calc_determinant(matrix,depth=0):
        if matrix.shape ==(2,2):
            return matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]
        else:# if the shape is (3,3) or higher
            result=0
            for i in range(len(matrix)):
                helper = np.delete(matrix,i,axis=1)
                helper = np.delete(helper,0,axis=0)
                result+= (-1)**i * matrix[0][i]* calc_determinant(helper,depth+1)
            return result
    def calc_eigenvalue(result):
        # print(result)
        determinant = calc_determinant(result)
        # print(determinant)
        equation = Eq(determinant,0)
        return solve(equation,y)
    
    def calc_eigenvector(result, eigenvalues):
        eigenvectors = []
        for eigenvalue in eigenvalues:
            temp = result.copy()
            temp = np.array([[t.subs(y,eigenvalue) for t in row] for row in temp ])
            # print("array: ", temp)
        
            A = Matrix(temp)
            # print("Eigen value: ",eigenvalue," \n\n\n")
            # print(A)
            x_symbols= ''
            for i in range(np.array(A).shape[0]):
                if i+1!=np.array(A).shape[0]:
                    x_symbols+="x"+str(i+1)+" "
                else:
                    x_symbols+="x"+str(i+1)
            x = Matrix(symbols(x_symbols))
            eq = A *x
            # print(eq)
            solution = solve(eq, x)
            eigenvectors.append(solution)
        return eigenvectors
        
    y = symbols('y')
    idintity_matrix = np.zeros(matrix.shape);np.fill_diagonal(idintity_matrix,1)
    result =  y*idintity_matrix -matrix
    # print(result)
    eigenvalues = calc_eigenvalue(result)
    eigenvalues = [re(eigenvalue) for eigenvalue in eigenvalues]
    # print("eigenvalues: ",eigenvalues)
    eigenvectors =calc_eigenvector(result,eigenvalues)
    return eigenvalues,eigenvectors
    
# # Define the variable


# # Define the cubic equation
# equation = Eq(x**2 - (10*x)/3 + 0, 0)  # Example: x^3 - 6x^2 + 11x - 6 = 0

# # Solve the equation
# roots = solve(equation, x)

# print("The roots of the cubic equation are:", roots)
def covariance(values):
        return np.dot(values.T,values)/len(values)

# data =np.array( [
# [1616.68365449, -349.54543245],
#  [-349.54543245,  746.91878758],
#  ])
data = np.array([
    [1,7],
    [5,3],
    [3,5],
    [0,8],
    [4,4]
])
# eigen_values:  [1739.7481184   623.85432367]

covariance_matrix = covariance(data)

eigen_values, eigen_vectors = get_Eigens(covariance_matrix)

covariance_matrix,eigen_values,eigen_vectors

(array([[10.2, 10.6],
        [10.6, 32.6]]),
 [5.97923477903901, 36.8207652209610],
 [{x1: 0.0, x2: 0.0}, {x1: 0.0, x2: 0.0}])

In [18]:
import numpy as np

def calculate_determinant(matrix):
    """
    Calculate the determinant of a matrix recursively.
    """
    n = len(matrix)
    if n == 1:  # Base case for 1x1 matrix
        return matrix[0, 0]
    if n == 2:  # Base case for 2x2 matrix
        return matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]

    # Recursive case for larger matrices
    determinant = 0
    for col in range(n):
        submatrix = np.delete(np.delete(matrix, 0, axis=0), col, axis=1)
        determinant += ((-1) ** col) * matrix[0, col] * calculate_determinant(submatrix)
    return determinant

def find_eigenvalues(matrix):
    """
    Find eigenvalues by solving the characteristic polynomial.
    """
    n = len(matrix)
    identity = np.eye(n)
    eigenvalues = []
    for guess in np.linspace(-10, 10, 1000):  # Brute-force guesses for eigenvalues
        char_matrix = matrix - guess * identity
        if np.isclose(calculate_determinant(char_matrix), 0, atol=1e-5):
            if not any(np.isclose(guess, ev, atol=1e-3) for ev in eigenvalues):
                eigenvalues.append(guess)
    return eigenvalues

def find_eigenvectors(matrix, eigenvalues):
    """
    Find eigenvectors for each eigenvalue.
    """
    n = len(matrix)
    identity = np.eye(n)
    eigenvectors = []

    for eigenvalue in eigenvalues:
        char_matrix = matrix - eigenvalue * identity
        _, _, vh = np.linalg.svd(char_matrix)  # Null space via SVD
        null_space_vector = vh[-1]  # Last row corresponds to the null space
        eigenvectors.append(null_space_vector / np.linalg.norm(null_space_vector))
    
    return eigenvectors

def calculate_eigen(matrix):
    """
    Calculate eigenvalues and eigenvectors from scratch.
    """
    matrix = np.array(matrix, dtype=float)
    eigenvalues = find_eigenvalues(matrix)
    eigenvectors = find_eigenvectors(matrix, eigenvalues)
    return eigenvalues, eigenvectors

# Example usage
data = [
  [1616.68365449, -349.54543245,  -22.06700932, -123.4582571 ],
 [-349.54543245,  746.91878758,   -8.56294962,  486.42037881],
 [ -22.06700932,   -8.56294962,    7.4999359,     6.32702599],
 [-123.4582571,   486.42037881,    6.32702599,  582.59459241],
]

eigenvalues, eigenvectors = calculate_eigen(data)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
for vector in eigenvectors:
    print(vector)


Eigenvalues: []
Eigenvectors:


In [19]:
10/3

3.3333333333333335

In [20]:
from sympy import symbols, Eq, solve

# Define the variable
x = symbols('x')

# Define the cubic equation
equation = Eq(x**3 - 6*x**2 + 11*x - 6, 0)  # Example: x^3 - 6x^2 + 11x - 6 = 0

# Solve the equation
roots = solve(equation, x)

print("The roots of the cubic equation are:", roots)


The roots of the cubic equation are: [1, 2, 3]


In [21]:
def calc_determinant(matrix,depth=0):
    if matrix.shape ==(2,2):
        print("good job")
        return matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]
    else:# if the shape is (3,3) or higher
        result=0
        for i in range(len(matrix)):
            helper = np.delete(matrix,i,axis=1)
            helper = np.delete(helper,0,axis=0)
            print((-1)**i *matrix[0][i]," the depth is: ",depth)
            result+= (-1)**i * matrix[0][i]*calc_determinant(helper,depth+1)
        return result

In [22]:
data =np.array([
    [1,0,4,-6],
    [2,5,0,3],
    [-1,2,3,5],
    [2,1,-2,3]
])
calc_determinant(data)

1  the depth is:  0
5  the depth is:  1
good job
0  the depth is:  1
good job
3  the depth is:  1
good job
0  the depth is:  0
2  the depth is:  1
good job
0  the depth is:  1
good job
3  the depth is:  1
good job
4  the depth is:  0
2  the depth is:  1
good job
-5  the depth is:  1
good job
3  the depth is:  1
good job
6  the depth is:  0
2  the depth is:  1
good job
-5  the depth is:  1
good job
0  the depth is:  1
good job


318

In [23]:

temp= np.array([[1,2,3],
                [5,6,3],
                [5,2,1]])
k = np.delete(temp,0,axis=0)
# temp = np.delete(temp,1,axis=1)
(temp,k)

(array([[1, 2, 3],
        [5, 6, 3],
        [5, 2, 1]]),
 array([[5, 6, 3],
        [5, 2, 1]]))

In [24]:
x= symbols("x")
data = 3*x**2+50*4*x
data.(x,10)

SyntaxError: invalid syntax (3305703063.py, line 3)

In [108]:
x=40
data,x

(3*x**2 + 200*x, 40)

In [27]:
from sympy import symbols 
from sympy.matrices import Matrix
b = Matrix([0,0])
A.solve(b)

Matrix([
[0],
[0]])

In [31]:
import sympy as sp

# Define the matrix
A = sp.Matrix([[-4/3,-4/3],[-4/3,-2/3]])

# Define the vector
x = sp.Matrix(sp.symbols('x1 x2'))

# Define the equation A * x = 0
eq = A * x

# Solve the equation
solution = sp.solve(eq, x)

solution


{x1: 0.0, x2: 0.0}

In [49]:
from sympy import Matrix, symbols ,solve

# Define the matrix with rows that are the same but multiplied by some factor
A = Matrix([
[-2/3, -4/3, -2.0],
[-4/3, -8/3, 1],
[0, 0, 0]
])


# Define the vector
x = Matrix(symbols('x1 x2 x3'))

# Define the equation A * x = 0
eq = A * x

# Solve the equation for x
solution = solve(eq, x)

solution


{x1: -2.0*x2, x3: 0.0}

In [22]:
from sympy import Matrix, symbols

# Define the singular matrix of coefficients
A = Matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Define the right-hand side vector
b = Matrix([14, 32, 50])

# Solve the linear system using rref for general solutions
A.solve(b)


NonInvertibleMatrixError: Matrix det == 0; not invertible.

In [119]:
A = np.array([
   [ 1.,         -0.31809322, -0.20040206, -0.12721092],
 [-0.31809322,  1.,         -0.1144084,   0.73738083],
 [-0.20040206, -0.1144084,   1.,          0.09571668],
 [-0.12721092,  0.73738083,  0.09571668,  1.        ],
])

# Compute the null space of A
_, _, vh = np.linalg.svd(A)
null_space = vh[-1]  # The last row of V^H corresponds to the null space

# Normalize the null space vector for better representation
null_space_normalized = null_space / np.linalg.norm(null_space)

null_space_normalized

array([-0.23462496, -0.70171674, -0.23244323,  0.63128036])