In [1]:
import numpy as np

In [2]:
cofficients = [1,-8/3,0]

<span style="background-color:green">X**2 - x*10/3 +0=0<span>
<br>
(x=0), (x=10/3)

In [ ]:
from sympy import symbols, Eq, solve, Matrix, re, simplify

class get_Eigens():
    def __init__(self):
        pass
    def calc_determinant(self,matrix,depth=0):
        if matrix.shape ==(2,2):
            return matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]
        else:# if the shape is (3,3) or higher
            result=0
            for i in range(len(matrix)):
                helper = np.delete(matrix,i,axis=1)
                helper = np.delete(helper,0,axis=0)
                result+= (-1)**i * matrix[0][i]* self.calc_determinant(helper,depth+1)
            return result
        
    def calc_eigenvalue(self,matrix):
        y = symbols('y')
        idintity_matrix = np.zeros(matrix.shape);np.fill_diagonal(idintity_matrix,1)
        result =  matrix- y*idintity_matrix
        determinant = self.calc_determinant(result)
        equation = Eq(determinant,0)
        
        return solve(equation,y)
    
    def calc_eigenvector(self,result, eigenvalues):
        eigenvectors = []#note the result must equalt to 8, 5, 4 and 3
        for eigenvalue in eigenvalues:
            temp = result.copy()
            shifted = np.zeros(result.shape);np.fill_diagonal(shifted,eigenvalue)
            temp = temp - shifted
            # print(temp)
            # print("determinant of eigen value ",eigenvalue,": ", self.calc_determinant(temp))
        
            # A = Matrix(temp)
            # x_symbols= ''
            # for i in range(np.array(A).shape[0]):
            #     if i+1!=np.array(A).shape[0]:
            #         x_symbols+="x"+str(i+1)+" "
            #     else:
            #         x_symbols+="x"+str(i+1)
            # x = Matrix(symbols(x_symbols))
            # eq = A *x
            # solution = solve(eq, x)
            # eigenvectors.append(solution)
            u,_, v = np.linalg.svd(temp)
            print("uuuuuuu:\n",u)
            print("\n\nvvvvvv\n",v)
            eigenvector = vh[-1]  # The eigenvector corresponds to the smallest singular value
            eigenvectors.append(eigenvector)
        
        return eigenvectors
    def main(self,matrix):
        
        # print(result)
        eigenvalues = self.calc_eigenvalue(matrix)
        eigenvalues = [float(re(eigenvalue)) for eigenvalue in eigenvalues]
        print("eigenvalues: ",eigenvalues)
        eigenvectors =self.calc_eigenvector(matrix,eigenvalues)
        return eigenvalues,eigenvectors
    
# # Define the variable


# # Define the cubic equation
# equation = Eq(x**2 - (10*x)/3 + 0, 0)  # Example: x^3 - 6x^2 + 11x - 6 = 0

# # Solve the equation
# roots = solve(equation, x)

# print("The roots of the cubic equation are:", roots)
def covariance(values):
        return np.dot(values.T,values)/len(values)

# data =np.array( [
# [1616.68365449, -349.54543245],
#  [-349.54543245,  746.91878758],
#  ])

# eigen_values:  [1739.7481184   623.85432367]
data = np.array([
  [1616.68365449, -349.54543245,  -22.06700932],
 [-349.54543245,  746.91878758,   -8.56294962],
 [ -22.06700932,   -8.56294962,    7.4999359 ],
])
covariance_matrix = covariance(data)
covariance_matrix = np.array([
  [1616.68365449, -349.54543245,  -22.06700932],
 [-349.54543245,  746.91878758,   -8.56294962],
 [ -22.06700932,   -8.56294962,    7.4999359 ],
])
get_eigen = get_Eigens()
eigen_values, eigen_vectors = get_eigen.main(covariance_matrix)
val,v  = np.linalg.eig(covariance_matrix)
# eigen_values[0],val[0]
eigen_vectors[np.argmax(eigen_values)],v[np.argmax(val)]
np.dot(eigen_vectors[0],eigen_vectors[1])

eigenvalues:  [6.928877178491143, 624.2389416617572, 1739.9345591297517]
uuuuuuu:
 [[-0.94324473 -0.33160656  0.01806836]
 [ 0.33193638 -0.94308756  0.02010235]
 [ 0.01037398  0.02495898  0.99963465]]


vvvvvv
 [[-0.94324473  0.33193638  0.01037398]
 [-0.33160656 -0.94308756  0.02495898]
 [ 0.01806836  0.02010235  0.99963465]]


NameError: name 'vh' is not defined

In [4]:
import numpy as np

def custom_eig(matrix):
    """
    Computes the eigenvalues and eigenvectors of a square matrix.

    Parameters:
        matrix (ndarray): A square 2D NumPy array.

    Returns:
        eigenvalues (ndarray): An array of eigenvalues.
        eigenvectors (ndarray): A 2D array where each column is an eigenvector.
    """
    # Ensure the input is a square matrix
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Input must be a square matrix.")

    # Step 1: Compute the eigenvalues (roots of the characteristic polynomial)
    print("the matrix:",matrix)
    identity = np.eye(matrix.shape[0])
    print(identity)
    coeffs = np.poly(matrix)
    print("cofficients: ", coeffs)  # Coefficients of the characteristic polynomial
    eigenvalues = np.roots(coeffs)
    print("eigenvalues:", eigenvalues)

    # Step 2: Compute the eigenvectors
    eigenvectors = []
    for eigenvalue in eigenvalues:
        # Solve (A - lambda * I) v = 0
        shifted_matrix = matrix - eigenvalue * identity
        print("determinant: ",shifted_matrix)
        _, _, vh = np.linalg.svd(shifted_matrix)
        eigenvector = vh[-1]  # The eigenvector corresponds to the smallest singular value
        eigenvectors.append(eigenvector)

    # Convert eigenvectors list to a 2D array (columns are eigenvectors)
    eigenvectors = np.array(eigenvectors).T

    return np.array(eigenvalues), eigenvectors

# Example usage
if __name__ == "__main__":
    matrix = np.array([
    [1616.68365449, -349.54543245,  -22.06700932],
 [-349.54543245,  746.91878758,   -8.56294962],
 [ -22.06700932,   -8.56294962,    7.4999359 ],
    ])

    eigenvalues, eigenvectors = custom_eig(matrix)
    print("Eigenvalues:", eigenvalues)
    print("Eigenvectors:", eigenvectors)


the matrix: [[1616.68365449 -349.54543245  -22.06700932]
 [-349.54543245  746.91878758   -8.56294962]
 [ -22.06700932   -8.56294962    7.4999359 ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
cofficients:  [ 1.00000000e+00 -2.37110238e+03  1.10251598e+06 -7.52569538e+06]
eigenvalues: [1739.93455913  624.23894166    6.92887718]
determinant:  [[ -123.25090464  -349.54543245   -22.06700932]
 [ -349.54543245  -993.01577155    -8.56294962]
 [  -22.06700932    -8.56294962 -1732.43462323]]
determinant:  [[ 992.44471283 -349.54543245  -22.06700932]
 [-349.54543245  122.67984592   -8.56294962]
 [ -22.06700932   -8.56294962 -616.73900576]]
determinant:  [[ 1.60975478e+03 -3.49545432e+02 -2.20670093e+01]
 [-3.49545432e+02  7.39989910e+02 -8.56294962e+00]
 [-2.20670093e+01 -8.56294962e+00  5.71058722e-01]]
Eigenvalues: [1739.93455913  624.23894166    6.92887718]
Eigenvectors: [[ 0.94324473  0.33160656  0.01806836]
 [-0.33193638  0.94308756  0.02010235]
 [-0.01037398 -0.02495898  0.99963465]]


In [5]:
import numpy as np

def find_row_dependency(matrix, tol=1e-10):
    """
    Find row dependencies in a matrix.

    Parameters:
        matrix (list of lists or numpy array): The matrix to analyze.
        tol (float): Tolerance to treat near-zero values as zero.

    Returns:
        dependencies (list): List of dependent rows and their relationships.
    """
    matrix = np.array(matrix, dtype=float)  # Convert to float for precision
    rows, cols = matrix.shape
    dependencies = []
    
    # Perform Gaussian elimination
    for i in range(min(rows, cols)):
        # Find the pivot (largest absolute value in column i below row i)
        pivot_row = np.argmax(np.abs(matrix[i:, i])) + i
        pivot_value = matrix[pivot_row, i]
        
        if abs(pivot_value) < tol:  # Pivot is too small, skip this column
            continue
        
        # Swap rows to place pivot on the diagonal
        matrix[[i, pivot_row]] = matrix[[pivot_row, i]]
        
        # Normalize pivot row
        matrix[i] = matrix[i] / matrix[i, i]
        
        # Eliminate below
        for j in range(i + 1, rows):
            matrix[j] -= matrix[j, i] * matrix[i]
    
    # Check for dependent rows
    for i in range(rows):
        if np.all(np.abs(matrix[i]) < tol):  # Row is effectively zero
            # Find dependency as linear combination
            dependency = f"Row {i} is dependent on: "
            factors = []
            
            for j in range(rows):
                if j != i and np.any(np.abs(matrix[j]) > tol):
                    factors.append(f"Row {j}")
            dependency += ", ".join(factors)
            dependencies.append(dependency)
    
    return dependencies

# Example
matrix = [
[ -123.25090464,  -349.54543245,   -22.06700932],
 [ -349.54543245,  -993.01577155,    -8.56294962],
 [  -22.06700932,    -8.56294962, -1732.43462323],
]

dependencies = find_row_dependency(matrix)
print("Row Dependencies:")
for dep in dependencies:
    print(dep)


Row Dependencies:


In [6]:
identity = np.eye(matrix.shape[0])
print(identity)
coeffs = np.poly(matrix)  # Coefficients of the characteristic polynomial
print(cofficients)
eigenvalues = np.roots(coeffs)

AttributeError: 'list' object has no attribute 'shape'

In [48]:
round(2.34898991e-16,6)

0.0

In [34]:
import numpy as np
from sympy import symbols, Eq, Matrix, solve, simplify

def calc_eigenvalue(self, matrix):
    y = symbols('y')
    
    # Convert matrix to symbolic form
    matrix_sym = Matrix(matrix)
    identity_matrix = Matrix.eye(matrix.shape[0])
    
    # Subtract y * identity_matrix from the matrix
    result = matrix_sym - y * identity_matrix
    
    # Calculate the determinant of the symbolic matrix
    determinant = result.det()
    
    # Solve for the eigenvalues (where determinant = 0)
    equation = Eq(determinant, 0)
    
    result = solve(equation, y)
    
    # Simplify the result
    simplified_result = [simplify(r) for r in result]
    
    # Numerical approximation and remove small imaginary parts
    numerical_result = [r.evalf() for r in simplified_result]
    
    # Remove small imaginary components (close to zero)
    numerical_result_real = [r.as_real_imag()[0] if abs(r.imag) < 1e-6 else r for r in numerical_result]

    print("Simplified Eigenvalues:", simplified_result)
    print("Numerical Approximation (Real):", numerical_result_real)
    
    return simplified_result, numerical_result_real

# Or, alternatively, using NumPy for a more direct approach:
def calc_eigenvalue_numpy(self, matrix):
    eigenvalues, _ = np.linalg.eig(matrix)
    
    # Round the eigenvalues to a reasonable precision (since they might be very close to 8, 5, 4, and 3)
    eigenvalues_rounded = np.round(eigenvalues, 6)
    
    print("Numerical Eigenvalues (rounded):", eigenvalues_rounded)
    return eigenvalues_rounded


In [22]:

eigenvalues, _ = np.linalg.eig(covariance_matrix)

# Round the eigenvalues to a reasonable precision (since they might be very close to 8, 5, 4, and 3)
eigenvalues_rounded = np.round(eigenvalues, 1)

print("Numerical Eigenvalues (rounded):", eigenvalues_rounded)
eigenvalues_rounded

Numerical Eigenvalues (rounded): [1.6+0.j  9.3+0.j  5.5+0.3j 5.5-0.3j]


array([1.6+0.j , 9.3+0.j , 5.5+0.3j, 5.5-0.3j])

In [ ]:
import numpy as np
from sympy import symbols, Eq, solve, Matrix, simplify

class GetEigens:
    def __init__(self):
        self.EPSILON = 1e-10  # Threshold for floating-point precision

    def calc_determinant(self, matrix):
        sym_matrix = Matrix(matrix)
        return sym_matrix.det()

    def calc_eigenvalue(self, matrix):
        y = symbols('y')
        identity_matrix = np.eye(matrix.shape[0])
        result = matrix - y * identity_matrix
        determinant = self.calc_determinant(result)
        equation = Eq(determinant, 0)
        return solve(equation, y)

    def calc_eigenvector(self, matrix, eigenvalues):
        eigenvectors = []
        for eigenvalue in eigenvalues:
            temp = matrix.copy()
            shifted = eigenvalue * np.eye(matrix.shape[0])
            temp = temp - shifted
            determinant = self.calc_determinant(temp)
            if abs(determinant) < self.EPSILON:
                print(f"Determinant of eigenvalue {eigenvalue}: approximately zero")
            else:
                print(f"Determinant of eigenvalue {eigenvalue}: {determinant}")
        return eigenvectors

    def main(self, matrix):
        eigenvalues = self.calc_eigenvalue(matrix)
        eigenvectors = self.calc_eigenvector(matrix, eigenvalues)
        return eigenvalues, eigenvectors


# Test the class
covariance_matrix = np.array([
    [4, 1, 2, 0],
    [3, 5, 0, 1],
    [2, 0, 6, 2],
    [0, 1, 2, 7],
])

get_eigen = GetEigens()
eigen_values, eigen_vectors = get_eigen.main(covariance_matrix)
print("Eigenvalues:", eigen_values)


Determinant of eigenvalue 1.64993734927255 + 0.e-21*I: approximately zero
Determinant of eigenvalue 5.53419012851438 - 0.25143793579411*I: approximately zero
Determinant of eigenvalue 5.53419012851438 + 0.25143793579411*I: approximately zero
Determinant of eigenvalue 9.28168239369869 + 0.e-21*I: approximately zero
Eigenvalues: [1.64993734927255 + 0.e-21*I, 5.53419012851438 - 0.25143793579411*I, 5.53419012851438 + 0.25143793579411*I, 9.28168239369869 + 0.e-21*I]


In [ ]:
import numpy as np
from sympy import symbols, Eq, solve, Matrix, simplify

class GetEigens:
    def __init__(self):
        self.EPSILON = 1e-10  # Threshold for floating-point precision

    def calc_determinant(self, matrix):
        sym_matrix = Matrix(matrix)
        return sym_matrix.det()

    def calc_eigenvalue(self, matrix):
        y = symbols('y')
        identity_matrix = np.eye(matrix.shape[0])
        result = matrix - y * identity_matrix
        determinant = self.calc_determinant(result)
        equation = Eq(determinant, 0)
        return solve(equation, y)

    def calc_eigenvector(self, matrix, eigenvalues):
        eigenvectors = []
        for eigenvalue in eigenvalues:
            # Shifted matrix (A - λI)
            shifted_matrix = Matrix(matrix - eigenvalue * np.eye(matrix.shape[0]))

            # Convert to symbolic for sympy's nullspace
            symbolic_matrix = shifted_matrix.applyfunc(simplify)

            # Compute null space
            null_space = symbolic_matrix.nullspace()
            if null_space:
                # Normalize the first eigenvector in the null space
                eigenvector = null_space[0]
                eigenvectors.append(eigenvector / eigenvector.norm())
            else:
                eigenvectors.append(None)  # No eigenvector found
        return eigenvectors

    def main(self, matrix):
        eigenvalues = self.calc_eigenvalue(matrix)
        eigenvectors = self.calc_eigenvector(matrix, eigenvalues)
        return eigenvalues, eigenvectors


# Test the class
covariance_matrix = np.array([
    [4, 1, 2, 0],
    [3, 5, 0, 1],
    [2, 0, 6, 2],
    [0, 1, 2, 7],
])

get_eigen = GetEigens()
eigen_values, eigen_vectors = get_eigen.main(covariance_matrix)

print("Eigenvalues:", eigen_values)
print("Eigenvectors:")
for vec in eigen_vectors:
    print(vec)


Eigenvalues: [1.64993734927255 + 0.e-21*I, 5.53419012851438 - 0.25143793579411*I, 5.53419012851438 + 0.25143793579411*I, 9.28168239369869 + 0.e-21*I]
Eigenvectors:
None
None
None
None


In [6]:
import numpy as np

def calculate_determinant(matrix):
    """
    Calculate the determinant of a matrix recursively.
    """
    n = len(matrix)
    if n == 1:  # Base case for 1x1 matrix
        return matrix[0, 0]
    if n == 2:  # Base case for 2x2 matrix
        return matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]

    # Recursive case for larger matrices
    determinant = 0
    for col in range(n):
        submatrix = np.delete(np.delete(matrix, 0, axis=0), col, axis=1)
        determinant += ((-1) ** col) * matrix[0, col] * calculate_determinant(submatrix)
    return determinant

def find_eigenvalues(matrix):
    """
    Find eigenvalues by solving the characteristic polynomial.
    """
    n = len(matrix)
    identity = np.eye(n)
    eigenvalues = []
    for guess in np.linspace(-10, 10, 1000):  # Brute-force guesses for eigenvalues
        char_matrix = matrix - guess * identity
        if np.isclose(calculate_determinant(char_matrix), 0, atol=1e-5):
            if not any(np.isclose(guess, ev, atol=1e-3) for ev in eigenvalues):
                eigenvalues.append(guess)
    return eigenvalues

def find_eigenvectors(matrix, eigenvalues):
    """
    Find eigenvectors for each eigenvalue.
    """
    n = len(matrix)
    identity = np.eye(n)
    eigenvectors = []

    for eigenvalue in eigenvalues:
        char_matrix = matrix - eigenvalue * identity
        _, _, vh = np.linalg.svd(char_matrix)  # Null space via SVD
        null_space_vector = vh[-1]  # Last row corresponds to the null space
        eigenvectors.append(null_space_vector / np.linalg.norm(null_space_vector))
    
    return eigenvectors

def calculate_eigen(matrix):
    """
    Calculate eigenvalues and eigenvectors from scratch.
    """
    matrix = np.array(matrix, dtype=float)
    eigenvalues = find_eigenvalues(matrix)
    eigenvectors = find_eigenvectors(matrix, eigenvalues)
    return eigenvalues, eigenvectors

# Example usage
data = [
  [1616.68365449, -349.54543245,  -22.06700932, -123.4582571 ],
 [-349.54543245,  746.91878758,   -8.56294962,  486.42037881],
 [ -22.06700932,   -8.56294962,    7.4999359,     6.32702599],
 [-123.4582571,   486.42037881,    6.32702599,  582.59459241],
]

eigenvalues, eigenvectors = calculate_eigen(data)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
for vector in eigenvectors:
    print(vector)


Eigenvalues: []
Eigenvectors:


In [7]:
10/3

3.3333333333333335

In [8]:
from sympy import symbols, Eq, solve

# Define the variable
x = symbols('x')

# Define the cubic equation
equation = Eq(x**3 - 6*x**2 + 11*x - 6, 0)  # Example: x^3 - 6x^2 + 11x - 6 = 0

# Solve the equation
roots = solve(equation, x)

print("The roots of the cubic equation are:", roots)


The roots of the cubic equation are: [1, 2, 3]


In [9]:
def calc_determinant(matrix,depth=0):
    if matrix.shape ==(2,2):
        print("good job")
        return matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]
    else:# if the shape is (3,3) or higher
        result=0
        for i in range(len(matrix)):
            helper = np.delete(matrix,i,axis=1)
            helper = np.delete(helper,0,axis=0)
            print((-1)**i *matrix[0][i]," the depth is: ",depth)
            result+= (-1)**i * matrix[0][i]*calc_determinant(helper,depth+1)
        return result

In [10]:
data =np.array([
    [1,0,4,-6],
    [2,5,0,3],
    [-1,2,3,5],
    [2,1,-2,3]
])
calc_determinant(data)

1  the depth is:  0
5  the depth is:  1
good job
0  the depth is:  1
good job
3  the depth is:  1
good job
0  the depth is:  0
2  the depth is:  1
good job
0  the depth is:  1
good job
3  the depth is:  1
good job
4  the depth is:  0
2  the depth is:  1
good job
-5  the depth is:  1
good job
3  the depth is:  1
good job
6  the depth is:  0
2  the depth is:  1
good job
-5  the depth is:  1
good job
0  the depth is:  1
good job


318

In [ ]:

temp= np.array([[1,2,3],
                [5,6,3],
                [5,2,1]])
k = np.delete(temp,0,axis=0)
# temp = np.delete(temp,1,axis=1)
(temp,k)

(array([[1, 2, 3],
        [5, 6, 3],
        [5, 2, 1]]),
 array([[5, 6, 3],
        [5, 2, 1]]))

In [ ]:
x= symbols("x")
data = 3*x**2+50*4*x
data.(x,10)

SyntaxError: invalid syntax (3305703063.py, line 3)

In [108]:
x=40
data,x

(3*x**2 + 200*x, 40)

In [27]:
from sympy import symbols 
from sympy.matrices import Matrix
b = Matrix([0,0])
A.solve(b)

Matrix([
[0],
[0]])

In [31]:
import sympy as sp

# Define the matrix
A = sp.Matrix([[-4/3,-4/3],[-4/3,-2/3]])

# Define the vector
x = sp.Matrix(sp.symbols('x1 x2'))

# Define the equation A * x = 0
eq = A * x

# Solve the equation
solution = sp.solve(eq, x)

solution


{x1: 0.0, x2: 0.0}

In [49]:
from sympy import Matrix, symbols ,solve

# Define the matrix with rows that are the same but multiplied by some factor
A = Matrix([
[-2/3, -4/3, -2.0],
[-4/3, -8/3, 1],
[0, 0, 0]
])


# Define the vector
x = Matrix(symbols('x1 x2 x3'))

# Define the equation A * x = 0
eq = A * x

# Solve the equation for x
solution = solve(eq, x)

solution


{x1: -2.0*x2, x3: 0.0}

In [22]:
from sympy import Matrix, symbols

# Define the singular matrix of coefficients
A = Matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Define the right-hand side vector
b = Matrix([14, 32, 50])

# Solve the linear system using rref for general solutions
A.solve(b)


NonInvertibleMatrixError: Matrix det == 0; not invertible.

In [119]:
A = np.array([
   [ 1.,         -0.31809322, -0.20040206, -0.12721092],
 [-0.31809322,  1.,         -0.1144084,   0.73738083],
 [-0.20040206, -0.1144084,   1.,          0.09571668],
 [-0.12721092,  0.73738083,  0.09571668,  1.        ],
])

# Compute the null space of A
_, _, vh = np.linalg.svd(A)
null_space = vh[-1]  # The last row of V^H corresponds to the null space

# Normalize the null space vector for better representation
null_space_normalized = null_space / np.linalg.norm(null_space)

null_space_normalized

array([-0.23462496, -0.70171674, -0.23244323,  0.63128036])