In [42]:
import pandas as pd
import numpy as np
from pca import PCA
import matplotlib.pyplot as plt


In [43]:
#6

In [44]:
dataframe = pd.DataFrame([
    [1,2],
    [2,4],
    [3,6]
])
data = dataframe.to_numpy()
dataframe.head()

0  1
0  1  2
1  2  4
2  3  6

In [45]:
def cosine_similarity(matrix1, matrix2):
    result = 0
    for index in range(len(matrix1)):
            dot_product = np.dot(matrix1[index], matrix2[index])
            norm_vec1 = np.linalg.norm(matrix1[index])
            norm_vec2 = np.linalg.norm(matrix2[index])
            cosine =  dot_product / (norm_vec1 * norm_vec2) 
            if cosine== 0: 
                  print("cosine is equal to zero")
            result +=cosine

    result/= len(matrix1) 
    return result
def info(data,reversed_data):
      print("cosine similiarity for data:\n",cosine_similarity(data,reversed_data),"\nMean Squared Error for data:\n",round(np.mean((data - reversed_data)**2),9))


In [46]:
pca = PCA(n_components=2)
pca.fit(data)
reduced_data = pca.transform(data)
reversed_data = pca.reverse(reduced_data)
info(data,reversed_data)

cosine similiarity for data:
 0.9999999999999999 
Mean Squared Error for data:
 0.0


In [47]:
(reduced_data[0],data[0],reversed_data[0])

(array([-2.23606798e+00, -2.22044605e-16]),
 array([1, 2], dtype=int64),
 array([1., 2.]))