In [13]:
import pandas as pd
import numpy as np
from pca import PCA
from fuzzy_entropy import FuzzyEntropy
import matplotlib.pyplot as plt

In [14]:
n_components=1
similarity = 0.5

In [15]:
dataframe = pd.read_excel("Book1.xlsx")
data = dataframe.to_numpy()
dataframe.head()

child_mort  exports  health  imports  income  inflation  life_expec  \
0        90.2     10.0    7.58     44.9    1610       9.44        56.2   
1        16.6     28.0    6.55     48.6    9930       4.49        76.3   
2        27.3     38.4    4.17     31.4   12900      16.10        76.5   
3       119.0     62.3    2.85     42.9    5900      22.40        60.1   
4        10.3     45.5    6.03     58.9   19100       1.44        76.8   

   total_fer   gdpp  
0       5.82    553  
1       1.65   4090  
2       2.89   4460  
3       6.16   3530  
4       2.13  12200

In [16]:
data = data[:,:]

In [17]:
class Converter:
    @staticmethod
    def convert_to_array(data_dict):
        data = []
        for key, value in data_dict.items():
            data=[key]
            data.extend(value)
        data= np.array(data)
        return data


In [18]:
def show(info,dim):
    f_data =[]
    colors= ["green", "red", "blue","yellow","orange","black","purple"]
    if dim <=3:
        if dim ==3:
            fig = plt.figure()
            ax = fig.add_subplot(111, projection='3d')

        for i,data_dic in enumerate(info.values()):
            final_data=Converter.convert_to_array(data_dic)
            if len(final_data) > len(f_data):
                f_data = final_data.copy()
            print("f data: ",len(f_data))

            if dim ==1:
                plt.scatter(range(len(final_data[:,0])),final_data[:,0],c=colors[i])
            elif dim ==2:
                plt.scatter(final_data[:,0],final_data[:,1],c=colors[i])
            else:
                
                x = final_data[:,0]
                y = final_data[:,1]
                z = final_data[:,2]
                if i%7==0:
                    i= i-1
                ax.scatter(x, y, z, c=colors[i], marker='o')
        plt.show()
        return f_data


In [19]:
f_data=None

In [20]:
pca = PCA(n_components=9)
pca.fit(data)
reduced_data = pca.transform(data)
# model = FuzzyEntropy()
# info =model.fit(reduced_data,s=similarity)

#Reduced To:  5 , Number of Classes:  2
# [4407.65986488   49.5632381  -375.77007066  278.51072448 1068.77329766]
# actual:
#  [  90.2    10.      7.58   44.9  1610.  ]

eigen function


In [21]:
compoentn = pca.components.T[:8]
(np.dot(np.dot(data[0],compoentn.T),compoentn)
,data[0])

(array([  52.22450263,   50.178187  ,    7.58642116,   44.913543  ,
        1609.97930311,    9.43782266,   56.19367195,    5.81202308,
         553.00048821]),
 array([  90.2 ,   10.  ,    7.58,   44.9 , 1610.  ,    9.44,   56.2 ,
           5.82,  553.  ]))

In [22]:
2.94111761e+00

2.94111761

In [23]:
for t in range(3):
    pca = PCA(n_components=t+1)
    pca.fit(data)
    reduced_data = pca.transform(data)
    model = FuzzyEntropy()
    info =model.fit(reduced_data,s=similarity)
    print("Reduced To: ",reduced_data.shape[1],", Number of Classes: ",len(info))
    print(pca.reverse(reduced_data)[0])
    f_data =show(info,dim=t+1)
    # [90.04991964 17.45184144  6.24345231 32.31991784]



eigen function


Reduced To:  1 , Number of Classes:  5
[  54.26736157   30.97654814    6.31491266   44.62366416 2744.10861662
    9.29966847   66.31822287    3.51854619 -646.95041244]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
len(f_data)

126